import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';

export const exportSemesterPdf = (semester, days, stats) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const capitalize = (s) => s ? s.charAt(0).toUpperCase() + s.slice(1) : 'Blank';

  // ---- Header ----
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(74, 111, 220);
  doc.text('SemesterTrack', 14, 22);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(108, 117, 125);
  doc.text('Academic Semester Planner', 14, 28);

  doc.setDrawColor(74, 111, 220);
  doc.setLineWidth(0.5);
  doc.line(14, 32, pageWidth - 14, 32);

  // ---- Semester Name ----
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(52, 58, 64);
  doc.text(semester.name, 14, 42);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(108, 117, 125);
  doc.text(
    `${format(new Date(semester.startDate), 'MMM dd, yyyy')} — ${format(new Date(semester.endDate), 'MMM dd, yyyy')}`,
    14, 49
  );

  // ---- Stats Boxes ----
  const statsY = 57;
  const boxW = 28;
  const boxH = 20;
  const gap = 3;

  const statsList = [
    { label: 'Total', value: stats.total, color: [52, 58, 64] },
    { label: 'Working', value: stats.working, color: [74, 111, 220] },
    { label: 'Holidays', value: stats.holiday, color: [40, 167, 69] },
    { label: 'Events', value: stats.event, color: [255, 193, 7] },
    { label: 'Exams', value: stats.exam, color: [220, 53, 69] },
    { label: 'Break', value: stats.break || 0, color: [23, 162, 184] }
  ];

  statsList.forEach((s, i) => {
    const x = 14 + i * (boxW + gap);
    doc.setFillColor(248, 249, 250);
    doc.roundedRect(x, statsY, boxW, boxH, 2, 2, 'F');
    doc.setFillColor(...s.color);
    doc.rect(x, statsY + boxH - 2, boxW, 2, 'F');

    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...s.color);
    doc.text(String(s.value), x + boxW / 2, statsY + 10, { align: 'center' });

    doc.setFontSize(6);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(108, 117, 125);
    doc.text(s.label, x + boxW / 2, statsY + 16, { align: 'center' });
  });

  // ---- Days Table ----
  const getTypeColor = (type) => {
    switch (type?.toLowerCase()) {
      case 'working': return [74, 111, 220];
      case 'holiday': return [40, 167, 69];
      case 'event': return [200, 160, 0];
      case 'exam': return [220, 53, 69];
      case 'break': return [23, 162, 184];
      default: return [108, 117, 125];
    }
  };

  const tableBody = days.map(day => {
    const d = day.date instanceof Date ? day.date : new Date(day.date);
    return [
      format(d, 'MMM dd, yyyy'),
      format(d, 'EEEE'),
      capitalize(day.type),
      day.description || ''
    ];
  });

  // Use autoTable as a function (works with all versions)
  autoTable(doc, {
    startY: statsY + boxH + 8,
    head: [['Date', 'Day', 'Type', 'Description']],
    body: tableBody,
    headStyles: {
      fillColor: [74, 111, 220],
      textColor: 255,
      fontStyle: 'bold',
      fontSize: 9
    },
    styles: {
      fontSize: 8,
      cellPadding: 3,
      textColor: [52, 58, 64]
    },
    columnStyles: {
      0: { cellWidth: 30 },
      1: { cellWidth: 25 },
      2: { cellWidth: 22 },
      3: { cellWidth: 'auto' }
    },
    alternateRowStyles: { fillColor: [248, 249, 250] },
    didParseCell: (data) => {
      if (data.section === 'body' && data.column.index === 2) {
        data.cell.styles.textColor = getTypeColor(data.cell.raw);
        data.cell.styles.fontStyle = 'bold';
      }
    },
    didDrawPage: (data) => {
      const ph = doc.internal.pageSize.getHeight();
      doc.setFontSize(7);
      doc.setTextColor(180);
      doc.text(
        `Generated by SemesterTrack on ${format(new Date(), 'MMM dd, yyyy HH:mm')}`,
        14,
        ph - 8
      );
      doc.text(
        `Page ${data.pageNumber}`,
        pageWidth - 14,
        ph - 8,
        { align: 'right' }
      );
    }
  });

  // Save
  const fileName = semester.name
    .replace(/[^a-zA-Z0-9 ]/g, '')
    .replace(/\s+/g, '_');
  doc.save(`${fileName}_Schedule.pdf`);
};